{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: machine-controller-manager-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: machine-controller-manager
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: machine-controller-manager-provider-gcp
      minAllowed:
        cpu: {{ .Values.resources.mcmProviderGCP.requests.cpu }}
        memory: {{ .Values.resources.mcmProviderGCP.requests.memory }}
      maxAllowed:
        cpu: {{.Values.resources.mcmProviderGCP.maxAllowed.cpu}}
        memory: {{.Values.resources.mcmProviderGCP.maxAllowed.memory}}
      controlledValues: RequestsOnly
    - containerName: gcp-machine-controller-manager
      minAllowed:
        cpu: {{ .Values.resources.mcm.requests.cpu }}
        memory: {{ .Values.resources.mcm.requests.memory }}
      controlledValues: RequestsOnly
{{- end }}
