{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.resourceLabels }}
  labels: {{- toYaml $machineClass.resourceLabels | nindent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.operatingSystem }}
  labels: {{- toYaml $machineClass.operatingSystem | nindent 4 }}
{{- end }}
{{- if $machineClass.nodeTemplate }}
nodeTemplate:
  architecture: {{ $machineClass.nodeTemplate.architecture }}
  capacity: {{- toYaml $machineClass.nodeTemplate.capacity | nindent 4 }}
  {{- if $machineClass.nodeTemplate.virtualCapacity }}
  virtualCapacity:
{{ toYaml $machineClass.nodeTemplate.virtualCapacity | indent 4 }}
  {{- end }}
  instanceType: {{ $machineClass.nodeTemplate.instanceType }}
  region: {{ $machineClass.nodeTemplate.region }}
  zone: {{ $machineClass.nodeTemplate.zone }}
{{- end }}
providerSpec:
  canIpForward: {{ $machineClass.canIpForward }}
  deletionProtection: {{ $machineClass.deletionProtection }}
  description: {{ $machineClass.description }}
  disks: {{- toYaml $machineClass.disks | nindent 2 }}
{{- if $machineClass.gpu }}
  gpu: {{- toYaml $machineClass.gpu | nindent 4 }}
{{- end }}
{{- if $machineClass.labels }}
  labels: {{- toYaml $machineClass.labels | nindent 4 }}
{{- end }}
  machineType: {{ $machineClass.machineType }}
{{- if $machineClass.metadata }}
  metadata: {{- toYaml $machineClass.metadata | nindent 2 }}
{{- end }}
{{- if $machineClass.minCpuPlatform }}
  minCpuPlatform: {{ $machineClass.minCpuPlatform }}
{{- end }}
  networkInterfaces: {{- toYaml $machineClass.networkInterfaces | nindent 2 }}
  scheduling:
    automaticRestart: {{ $machineClass.scheduling.automaticRestart }}
    onHostMaintenance: {{ $machineClass.scheduling.onHostMaintenance }}
    preemptible: {{ $machineClass.scheduling.preemptible }}
{{- if $machineClass.serviceAccounts }}
  serviceAccounts: {{- toYaml $machineClass.serviceAccounts | nindent 2 }}
{{- end }}
{{- if $machineClass.tags }}
  tags: {{- toYaml $machineClass.tags | nindent 2 }}
{{- end }}
  region: {{ $machineClass.region }}
  zone: {{ $machineClass.zone }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
provider: "GCP"
{{- end }}
