{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.resourceLabels }}
  labels:
{{ toYaml $machineClass.resourceLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.operatingSystem }}
  labels:
{{ toYaml $machineClass.operatingSystem | indent 4 }}
{{- end }}
{{- if $machineClass.nodeTemplate }}
nodeTemplate:
  capacity:
{{ toYaml $machineClass.nodeTemplate.capacity | indent 4 }}
  instanceType: {{ $machineClass.nodeTemplate.instanceType }}
  region: {{ $machineClass.nodeTemplate.region }}
  zone: {{ $machineClass.nodeTemplate.zone }}
{{- end }}
providerSpec:
  canIpForward: {{ $machineClass.canIpForward }}
  deletionProtection: {{ $machineClass.deletionProtection }}
  description: {{ $machineClass.description }}
  disks:
{{ toYaml $machineClass.disks | indent 2 }}
{{- if $machineClass.gpu }}
  gpu:
{{ toYaml $machineClass.gpu | indent 4 }}
{{- end }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
  machineType: {{ $machineClass.machineType }}
{{- if $machineClass.metadata }}
  metadata:
{{ toYaml $machineClass.metadata | indent 2 }}
{{- end }}
{{- if $machineClass.minCpuPlatform }}
  minCpuPlatform: {{ $machineClass.minCpuPlatform }}
{{- end }}
  networkInterfaces:
{{ toYaml $machineClass.networkInterfaces | indent 2 }}
  scheduling:
    automaticRestart: {{ $machineClass.scheduling.automaticRestart }}
    onHostMaintenance: {{ $machineClass.scheduling.onHostMaintenance }}
    preemptible: {{ $machineClass.scheduling.preemptible }}
{{- if $machineClass.serviceAccounts }}
  serviceAccounts:
{{ toYaml $machineClass.serviceAccounts | indent 2 }}
{{- end }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 2 }}
{{- end }}
  region: {{ $machineClass.region }}
  zone: {{ $machineClass.zone }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
credentialsSecretRef:
  name: {{ $machineClass.credentialsSecretRef.name }}
  namespace: {{ $machineClass.credentialsSecretRef.namespace }}
provider: "GCP"
{{- end }}
