{{- if .Values.imageVectorOverwrite }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-imagevector-overwrite
  namespace: {{ .Release.Namespace }}
  labels: {{- include "labels" . | nindent 4 }}
data:
  images_overwrite.yaml: |
  {{- .Values.imageVectorOverwrite | indent 4 }}
{{- end }}
